### ISSUE TITLE
Random fork/exec bug

### ISSUE THREAD

**Issue by Tonkpils** [Tonkpils/snag#10]
Every now and then we get this running tests

```
fork/exec /var/folders/g4/457m2vdj7ql9wn4sgjtjf8t00000gn/T/go-build320028182/github.com/Tonkpils/snag/_test/snag.test: exec format error
```

**Comment by zabawaba99** [comment]
Just a note - i've only ever seen this happen in the snag project itself, not other projects.

**Comment by Tonkpils** [comment]
I just found the issue...It's a space in the test args
