### ISSUE TITLE
Handle the response of b.watch()

### ISSUE THREAD

**Issue by zabawaba99** [Tonkpils/snag#34]
Should we be handling the return of [b.watch](https://github.com/Tonkpils/snag/blob/548cc136c4e0b1576b79cdf8ccf9714b3a76640d/builder.go#L64) inside of bob.Watch()?

If this function returns `false` signifying that it shouldn't build, should we bail out?

**Comment by Tonkpils** [comment]
The problem with that watch is that is the initial one that loads the working directory. If we bail out then no build will ever happen.

**Comment by zabawaba99** [comment]
Would that function ever return false the first time?

**Comment by zabawaba99** [comment]
> Would that function ever return false the first time?

Nope. It would only return false if there is no file in the current directory, which is not possible since they will always have the `.snag.yml`
