### ISSUE TITLE
Why is a `init` required?

### ISSUE THREAD

**Issue by 140am** [Tonkpils/snag#63]
After upgrading `snag` i noticed a configuration file is now required in the directory I want to use it in. The readme mentions sane default ignores and the created `.config.yml` is an example of things I can customize so I am trying to understand why the init per directory is now _required_? :neckbeard:

**Comment by zabawaba99** [comment]
The purpose of the `init` command was to allow users to create a quick `.snag.yml` file in whatever directory they're in. While running the command is not required, having a `.snag.yml` file in the directory that you're running snag in has always been required. The only way to bypass having that file in your directory is to use the `-c` flags when running the snag command (Refer to the [quick-use](https://github.com/Tonkpils/snag#quick-use) section of the README).

If you'd like to give us some more details as to your project structure and how you're using snag, we'd be happy to help find a solution that works for you.

**Comment by 140am** [comment]
Thank's for the quick response! The version of `snag` I was using does not seem to actually have a `-version` option :D but it is/was running `go build/test/vet` within `./...` "package path" on each cycle so after finally upgrading to 1.+ I was expecting the same golang biased defaults. Defiantly like the language/neutral tool direction and combination of using `-c` with list of commands and/or config 👍

**Comment by zabawaba99** [comment]
Glad you were able to resolve your issue! Please feel free to reach out again if you come across any issues or have a feature request. Happy snagging. 🍰
