### ISSUE TITLE
Enhance snag's output

### ISSUE THREAD

**Issue by Tonkpils** [Tonkpils/snag#9]
There are a few improvements I can think of with regards of snag's output. 
- [x] Give feedback during command execution (e.g, running, started, ended?)
- [x] It'd be nice to display nice formatting on logs from snag vs command's logs.

**Comment by zabawaba99** [comment]
Seems like you beat me to writing the issue :)

**Comment by zabawaba99** [comment]
We could probably use http://golang.org/pkg/text/tabwriter/ . However, from the looks of it we would have to buffer the command output and print it out when it finishes it. Doing that would also provide a cleaner solution for the first bit a well.

**Comment by zabawaba99** [comment]
I would call this done by 9d0e013 and 450fbcfbea760b7a3757a93ea598f2d43d8de4cb. It prefix's all `snag` output with `snag` and give status of the command that is running.
